import type { Metadata } from "next";
import { DriverLayout } from "./layout/driverLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function driverLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <DriverLayout>{children}</DriverLayout>;
}
