import type { Metadata } from "next";
import { useState } from "react";
import { SidebarContext } from "./layout-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const handleToggleSidebar = () => {
    setSidebarOpen(!sidebarOpen);
  };
  return (
    <SidebarContext.Provider
      value={{ collapsed: sidebarOpen, setCollapsed: handleToggleSidebar }}
    >
      {children}
    </SidebarContext.Provider>
  );
}
