import type { Metadata } from "next";
import NavBar from "./components/shared/NavBar";
import Footer from "./components/shared/Footer";
import { userInfo } from "./action/authAction";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await userInfo();

  return (
    <>
      <NavBar user={user} />
      <div className="mx-auto container">{children}</div>
      <Footer />
    </>
  );
}
